### ISSUE TITLE
psycopg2 library not loaded

### ISSUE THREAD

**Issue by skavie** [skavie/scrape#2]
When using Flask-migrate and Alembic to migrate DB schema changes into the database, the process errors out.

> (scrape) Andys-MacBook-Air:scrape andygan$ python manage.py db migrate
> Traceback (most recent call last):
>   File "manage.py", line 17, in <module>
>     manager.run()
>   File "/Users/andygan/Dropbox/Projects/Uwisukiyu/code/scrape/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
>     result = self.handle(sys.argv[0], sys.argv[1:])
>   File "/Users/andygan/Dropbox/Projects/Uwisukiyu/code/scrape/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
>     res = handle(*args, **config)
>   File "/Users/andygan/Dropbox/Projects/Uwisukiyu/code/scrape/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
>     return self.run(*args, **kwargs)
>   File "/Users/andygan/Dropbox/Projects/Uwisukiyu/code/scrape/lib/python2.7/site-packages/flask_migrate/__init__.py", line 177, in migrate
>     version_path=version_path, rev_id=rev_id)
>   File "/Users/andygan/Dropbox/Projects/Uwisukiyu/code/scrape/lib/python2.7/site-packages/alembic/command.py", line 117, in revision
>     script_directory.run_env()
>   File "/Users/andygan/Dropbox/Projects/Uwisukiyu/code/scrape/lib/python2.7/site-packages/alembic/script/base.py", line 407, in run_env
>     util.load_python_file(self.dir, 'env.py')
>   File "/Users/andygan/Dropbox/Projects/Uwisukiyu/code/scrape/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
>     module = load_module_py(module_id, path)
>   File "/Users/andygan/Dropbox/Projects/Uwisukiyu/code/scrape/lib/python2.7/site-packages/alembic/util/compat.py", line 79, in load_module_py
>     mod = imp.load_source(module_id, path, fp)
>   File "migrations/env.py", line 87, in <module>
>     run_migrations_online()
>   File "migrations/env.py", line 70, in run_migrations_online
>     poolclass=pool.NullPool)
>   File "/Users/andygan/Dropbox/Projects/Uwisukiyu/code/scrape/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 428, in engine_from_config
>     return create_engine(url, **options)
>   File "/Users/andygan/Dropbox/Projects/Uwisukiyu/code/scrape/lib/python2.7/site-packages/sqlalchemy/engine/__init__.py", line 387, in create_engine
>     return strategy.create(*args, **kwargs)
>   File "/Users/andygan/Dropbox/Projects/Uwisukiyu/code/scrape/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 80, in create
>     dbapi = dialect_cls.dbapi(**dbapi_args)
>   File "/Users/andygan/Dropbox/Projects/Uwisukiyu/code/scrape/lib/python2.7/site-packages/sqlalchemy/dialects/postgresql/psycopg2.py", line 580, in dbapi
>     import psycopg2
>   File "/Users/andygan/Dropbox/Projects/Uwisukiyu/code/scrape/lib/python2.7/site-packages/psycopg2/__init__.py", line 50, in <module>
>     from psycopg2._psycopg import BINARY, NUMBER, STRING, DATETIME, ROWID
> ImportError: dlopen(/Users/andygan/Dropbox/Projects/Uwisukiyu/code/scrape/lib/python2.7/site-packages/psycopg2/_psycopg.so, 2): Library not loaded: libssl.1.0.0.dylib
>   Referenced from: /Users/andygan/Dropbox/Projects/Uwisukiyu/code/scrape/lib/python2.7/site-packages/psycopg2/_psycopg.so
>   Reason: image not found

**Comment by skavie** [comment]
Fixed on the OS. symbolic link added. Resolved and noted in this commit:

https://github.com/skavie/scrape/commit/6b08526d8cfda5e2c1e982037bc57b95d9b744fd
